service: serverless-js-template
frameworkVersion: '2'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    DEBUG_LOGGING: ${env:DEBUG_LOGGING , true}
  apiGateway:
    shouldStartNameWithService: true

functions:
  hello:
    handler: src/functions/hello-world/handler.main
    events:
      - http:
          path: /helloWorld
          method: post
          cors: true
